### ISSUE TITLE
criar uma estrutura de pasta e fazer deploy 

### ISSUE THREAD

**Issue by JCDMeira** [akaaua/cropTracker#2]
Uma estrutura de pasta é essencial para organizar o projeto, principalmente se ele escalar e se tornar grande. Assim como o deploy é importante, pois mostra o resultado do que você fez, e muitas fezes recrutadores não sabem código, então vão se orientar por um bom readme e o deploy para avaliar o seu trabalho.

- [x] criar pasta assets
- [x] criar pasta css dentro de assets
- [x] mover images para dentro de assets
- [x] criar pasta js dentro de assets
- [x] mover arquivos de css e js para dentro das pastas de cada um
- [x] #3

Opcionalmente da pra criar uma pasta para guardar o html que não seja index também, mas isso vou deixar a seu cargo

**Comment by akaaua** [comment]
Thank you JCDMeira for the tips, i expect i got it correct now.
